### ISSUE TITLE
Can I translate this book in Bengali?

### ISSUE THREAD

**Issue by rafidalhaque** [mattcone/markdown-guide-book#11]
Hello @mattcone,

This book of yours is very informative. So, I wanted to translate this in Bengali; my native language for the Bengali Speakers. I will be gratefull to you if you permitted me to translate this book in Bengali.

Faithfully yours,
Rafid Al Haque

**Comment by mattcone** [comment]
Hey there @rafidalhaque! Yes, I would love to have the book translated in other languages. I think the process is fairly straightforward — you can fork the repository and start translating, then I'll add your translation in Leanpub. This article provides an overview: http://help.leanpub.com/en/articles/117487-i-would-like-to-translate-a-leanpub-book-what-should-i-do

Let me know if you have any questions: matt@macinstruct.com. Thanks!
