### ISSUE TITLE
Missing word/Grammar

### ISSUE THREAD

**Issue by aarongeorge** [mattcone/markdown-guide-book#13]
In the epub Introduction under the Beginner Resources it has the following sentence: “It also presents some +[of] the applications you can use to write -[using] Markdown.”

The words with [] around them are the problems, and the + and - are to denote adding the word or removing it.

Ideal result is "It also presents some of the applications you can use to write Markdown."

**Comment by mattcone** [comment]
Oof. Thank you for reporting this! I've fixed it in https://github.com/mattcone/markdown-guide-book/commit/f71fd5f845c7a34797ec8dfbcb567ce2ba43ad52.
