### ISSUE TITLE
Procedure to produce book from this source???

### ISSUE THREAD

**Issue by wxguy** [mattcone/markdown-guide-book#5]
A small documentation or build file which explain the build process of markdown to pdf or epub would be nice. Because, your book looks nice with NOTE (admonition) which I have seen any documentation to include in the official or unofficial markdown documentaion.

**Comment by mattcone** [comment]
Hey! I use [Leanpub](https://leanpub.com) to create the book. You can find the style guide and the instructions for the build process on their website:

- https://leanpub.com/lfm/read
- https://leanpub.com/manual/read

Hope this helps!
