### ISSUE TITLE
[Questions] How generate pdf

### ISSUE THREAD

**Issue by ventoh** [mattcone/markdown-guide-book#6]
Thank you for sharing the book. I have a question: how have you generated the pdf with the cover like your on leanpub? I looked at the file Book.txt but i think you have used a thirdy party tool. Can you help me?
Thank you.

**Comment by mattcone** [comment]
Hi! So Leanpub provides two methods to specify cover art — you can upload the file using their interface, or you can add the file in your repository. I had uploaded the file using their interface, but I just uploaded the cover artwork file in c695fda so I'll start using that method. You can see the Leanpub settings below. Hope this helps shed some light on things.

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/40424/71181750-f822e600-2231-11ea-81df-82bd8d045d83.png">

**Comment by ventoh** [comment]
Thank you. But what about generate the pdf without leanpub? Have you a command line (or other) tool with appropriate options to create the pdf?

**Comment by mattcone** [comment]
> But what about generate the pdf without leanpub? Have you a command line (or other) tool with appropriate options to create the pdf?

I use Leanpub to generate the PDF. I think you could probably do that too since you have the source. There are of course other tool chains you can use to generate PDFs (pandoc, gitbook) but I think the source files would require sustainable revision since I used a lot of stuff specific to Leanpub. Hope that helps.

**Comment by mattcone** [comment]
I use Leanpub's "Export Unbranded eBook" feature to generate all of the files. 

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/40424/71197641-514d4280-224f-11ea-9ec3-ceccd4a4f972.png">

**Comment by ventoh** [comment]
Very useful. Thank you very much.
